# Generated by Django 4.1.5 on 2023-01-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pause',
            new_name='guests_can_pause',
        ),
    ]
